apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  namespace: training
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ollama
  template:
    metadata:
      labels:
        name: ollama
    spec:
      containers:
      - name: ollama
        image: ollama/ollama:latest
        ports:
        - name: http
          containerPort: 11434
          protocol: TCP
          resources:
          requests:
           nvidia.com/gpu: 1 # Request 1 GPU
          limits:
           nvidia.com/gpu: 1 # Limit to 1 GPU