[OPENAI]
#OPENAI_KEY = <YOUR API KEY HERE>

[AzureOpenAI]
AZURE_OPENAI_API_KEY = "9adba277358e402d8da06f2e705896a4"
AZURE_OPENAI_EMBEDDING_MODEL_NAME = "hrisikesh-text-embedding-ada-002"
AZURE_OPENAI_ENDPOINT = "https://girishhrisikeshjyoti.openai.azure.com"
[PINECONE]
PINECONE_API_KEY = "43056291-5abc-4239-9d0a-f9f09f85dd13"

[LANGSMITH]
LANGSMITH_API_KEY = "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"
LANGCHAIN_PROJECT = "first-deployment"